### PR TITLE
Fixes #12

### LINKED ISSUE #12: Topics is not highlighted as recommend
Validation fails for laws metadata if there is no topic given, though the field is not marked as required.
Please add required label to the field.

### PR DESCRIPTION
**Pull request by acorbi**
@chris-aeviator please review, merge and deploy

### CODE REVIEW

**Comment by chris-aeviator** [comment]
checked in your change, but strangely it does not have any effect, can you confirm it works in your environment?

image

**Comment by acorbi** [comment]
@chris-aeviator I though it was just about making it mandatory but I think you mean showing the red asterisk right? Then see https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/pull/235

**Comment by chris-aeviator** [comment]
@acorbi 
sure it is both, also checked in https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/pull/235 , still no asterisk :alien:

**Comment by acorbi** [comment]
Then you have an issue on your dev env. Works for me....

#TIP: Look for files leftover non-remote-synced....

**Comment by chris-aeviator** [comment]
I will Check in about one hour!

---

Von unterwegs gesendet

**Pull request merged**
